# Source: bucketrepo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucketrepo-bucketrepo
  labels:
    app: bucketrepo-bucketrepo
    chart: "bucketrepo-0.1.53"
    release: bucketrepo
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
  namespace: jx
