# Source: jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-docker-cfg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: config.json
      key: config.json
      property: config.json
  template:
    type: Opaque
