# Source: jx-build-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerbuild
  labels:
    app: jx-build-controller
    chart: jx-build-controller-0.0.20
    release: jx-build-controller
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
  namespace: jx
